Section "Device"
    Identifier  "Configured Video Device"
    Driver      "vesa"
EndSection

Section "Screen"
    Identifier  "Default Screen"
    Device      "Configured Video Device"
    DefaultDepth 24
EndSection
